version: '3.9'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USERNAME=username
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  quality-assurance-api:
    
    depends_on:
      - db
    image: hamaschwany/qa-api
    environment:
      - DATABASE__HOST=db
      - DATABASE__USERNAME=username
      - DATABASE__PASSWORD=password
      - DATABASE__PORT=5432
      - DATABASE__NAME=mydb
      - JWT_SECRET_KEY_BASE=whatever
    ports:
      - 8080:3000