version: '3.1'
services:
  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
  app:
    image: hamaschwany/qa-api
    depends_on:
      - db
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      RAILS_MASTER_KEY: 9638af65728c2a902a05b1161a2d50c8